### ISSUE TITLE
Can jira-project-key be a regex?

### ISSUE THREAD

**Issue by rpopp-fni-stl-com** [cakeinpanic/jira-description-action#15]
As stated in the title, can I specify the jira-project-key value as a regex?  eg, (ABC|DEF|FNORD)

**Comment by cakeinpanic** [comment]
@rpopp-fni-stl-com unfortunately no, but you can use such config
custom-issue-number-regexp:  (ABC|DEF|FNORD)-\d+'

checkout this test case: https://github.com/cakeinpanic/jira-description-action/blob/master/__tests__/utils.test.ts#L54
