### ISSUE TITLE
Due to v1.x tags Dependabot is creating a PR for this action

### ISSUE THREAD

**Issue by javierjulio** [cakeinpanic/jira-description-action#26]
We have Dependabot configured to update any of our GitHub Actions so we had a PR created for jira-description-action v1.2 for some reason. I noticed there are v1.0, v1.1, and v1.2 git tags and I think that's why Dependabot is creating a PR to update from 0.3.2 to 1.2 when comparing the v1.x commits they are older.

<img width="812" alt="Screen Shot 2022-06-16 at 6 10 58 PM" src="https://user-images.githubusercontent.com/198547/174185272-742b1662-043f-4c0a-b2b8-933e2fde2625.png">

**Comment by cakeinpanic** [comment]
@javierjulio wow, it sucks!
Thank you for heads up, I think I'd just delete older versions

**Comment by javierjulio** [comment]
@cakeinpanic thank you!
