### ISSUE TITLE
Warning on running action: Node.js 12 actions are deprecated.

### ISSUE THREAD

**Issue by javierjulio** [cakeinpanic/jira-description-action#29]
I've noticed the following warning appear on a workflow run. I've included a screenshot of to what it looks like. It would help to have a new release using a supported version of Node. The warning suggests using Node 16.

> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: cakeinpanic/jira-description-action

<img width="973" alt="Screen Shot 2022-10-27 at 2 02 52 PM" src="https://user-images.githubusercontent.com/198547/198365003-29e0dad9-f595-4048-90f4-d71c1ab5b676.png">

**Comment by javierjulio** [comment]
Looks like there is a fix or partial fix in #27 already.

**Comment by cakeinpanic** [comment]
@javierjulio you seem to be right!
Thank you for the PR, merging it!
