### ISSUE TITLE
[request] Don't print Jira's API error to console

### ISSUE THREAD

**Issue by morficus** [cakeinpanic/jira-description-action#33]
When the referenced Jira ticket number is not found, the "raw" error from the Jira API is printed to the GitHub Workflow  console. Even when setting `fail-when-jira-issue-not-found` to `true` or `false`, the "raw" error is still displayed.

![Screenshot 2022-12-31 at 2 59 57 PM](https://user-images.githubusercontent.com/718799/210154573-e4384b25-0a2a-4e28-bcfb-6a812958d1b3.png)

The problem with doing this is that it is unnecessary noise; there is nothing actionable or meaningful. The meaningful bit is the message above that says "Jira key was not found".

**Comment by cakeinpanic** [comment]
Hi, basically this error is related to incorrect JIRA token provided not following the structure of `user email:api token'
It deserves better error message, you are completely right

**Comment by cakeinpanic** [comment]
error logging logic was improved, please see comment in this issue
https://github.com/cakeinpanic/jira-description-action/issues/42#issuecomment-1701169799
