### ISSUE TITLE
Can you release v0.3.4?

### ISSUE THREAD

**Issue by jduan-highnote** [cakeinpanic/jira-description-action#39]
The commit I'm interested in is https://github.com/cakeinpanic/jira-description-action/commit/eb1e91b20ac768c5dcb2c1845d5110b1d69eef19 because github actions no longer support node 12. I could use the `main` branch of this action in my workflow but I prefer to use a pinned version. Thanks!

**Comment by yotam707** [comment]
Plus one on that request please

**Comment by cakeinpanic** [comment]
easy!
0.4.0 is released
https://github.com/cakeinpanic/jira-description-action/releases/tag/v0.4.0

**Comment by jduan-highnote** [comment]
Thanks!
