### ISSUE TITLE
Make `use-branch-name` and `use-pr-title` separate values so they can be both set to true

### ISSUE THREAD

**Issue by khuongduybui** [cakeinpanic/jira-description-action#4]
Currently, the choice between branch name and PR title (as in where to look for JIRA issue keys) is XOR.

I'd like to be able to set both to true, which requires them to be separate config values.

**Comment by cakeinpanic** [comment]
Hi, @khuongduybui!
Can you please specify an example of how you name branches/PR's to understand the use case.

By now my thoughts are:
If there would be two sources of information, there should be priorities. So there is a need of third config value – to specify primary source. And maybe fourth, cause patterns of JIRA ticket inclusion can be different for branch name and PR title

Looks more like running action twice with different configs to avoid super bloated values list.
What do you think?

**Comment by khuongduybui** [comment]
Perhaps we are over-complicating the issue. Why don't we look for issue keys in both places (if both params are set to true) and add all found JIRA issue keys? Why there has to be only one?

**Comment by katyapavlenko** [comment]
@khuongduybui your wish is fulfilled :)
check updated readme and you are welcome to use v0.2.0 with parameter `use: 'both'`

**Comment by khuongduybui** [comment]
That is AWESOME! Thanks for quick turnaround.

**Comment by cakeinpanic** [comment]
@khuongduybui also pay attention on new changes introduced in 0.1.2 (regexp groups)
