### ISSUE TITLE
please report authentication error to the logs

### ISSUE THREAD

**Issue by alex-schwartzman-at-stratify** [cakeinpanic/jira-description-action#41]
When I specify a wrong token, the error message is very cryptic and does not give a hint that the authentication failed. 

Please, report the errors in an actionable manner. Otherwise I cannot distinguish if the issue is not found or authentication is not correct, or summary is missing in the ticket.

**Comment by cakeinpanic** [comment]
hi, thank you for raising this, logging was improved by https://github.com/cakeinpanic/jira-description-action/pull/43
please use`v0.5.1`
