### ISSUE TITLE
GHA running in a loop when authorizing the jira-token

### ISSUE THREAD

**Issue by ashwiniyerabati9** [cakeinpanic/jira-description-action#44]
Getting this error when i deauthorize the Jira token which is expected but when i authorize the jira-token, the github action works but runs in a loop. Not just this action all actions start to run in a loop. 

Deauthorized
<img width="1222" alt="Screenshot 2023-08-01 at 12 49 56 PM" src="https://github.com/cakeinpanic/jira-description-action/assets/80057657/e077419d-6a9a-43c1-8af8-b370b74cd3d5">

Authorized: GHA running in a loop

https://github.com/cakeinpanic/jira-description-action/assets/80057657/4bba54a7-71e9-4110-b5a7-b0f4f9ab6abc

**Comment by ashwiniyerabati9** [comment]
Looks like the pull_request type having edited and the description being updated are making the actions run in a loop.

**Comment by ashwiniyerabati9** [comment]
@cakeinpanic  - There are no other actions which are chained on the PR description.

**Comment by ashwiniyerabati9** [comment]
@cakeinpanic - Extract the ticket from the title and add to the description
Once the description is updated, GHA is still being executed in a loop and not breaking out of the action.

Is the looping action because of the action editing the PR? Can we get a confirmation on where the loop will break out in an expected flow.

**Comment by cakeinpanic** [comment]
@ashwiniyerabati9 loop happens because you have a trigger which is related to editing PR title. Please provide your workflow file so I can say for sure
