### ISSUE TITLE
Please Update your Releases and your Marketplace Page

### ISSUE THREAD

**Issue by bjrke** [cakeinpanic/jira-description-action#47]
According to your tags and the change log you released version 0.7.0 but the releases page (https://github.com/cakeinpanic/jira-description-action/releases) and the market place (https://github.com/marketplace/actions/jira-description) offer version 0.4.0 as latest. Not sure if its connected.

**Comment by cakeinpanic** [comment]
Thank you for your attention, I have updated it!
