### ISSUE TITLE
nodejs 20?

### ISSUE THREAD

**Issue by jduan-highnote** [cakeinpanic/jira-description-action#48]
node 16 has reached end of life. Any plan to move this action to use node 20?

**Comment by javierjulio** [comment]
I've opened a PR to resolve this. GitHub mentions a timeline of Spring 2024 which we are nearing so hopefully this can be addressed with a new release soon. Thanks for calling it out.

**Comment by jduan-highnote** [comment]
@javierjulio you're the hero!
