### ISSUE TITLE
Jira Basic Auth / Deprecation

### ISSUE THREAD

**Issue by hitmands** [cakeinpanic/jira-description-action#7]
My workflow is failing due to: 

![image](https://user-images.githubusercontent.com/5674833/102135086-59829280-3e4f-11eb-9412-910a27f4ecfa.png)

https://confluence.atlassian.com/cloud/deprecation-of-basic-authentication-with-passwords-for-jira-and-confluence-apis-972355348.html

- [ ] requires action update

**Comment by leovanhaaren** [comment]
Same here, @cakeinpanic can you update the action please?

**Comment by cakeinpanic** [comment]
@leovanhaaren @hitmands it works correctly in my projects where I useAPI token, I guess you tried to use your password directly.
please check this:
https://github.com/cakeinpanic/jira-description-action#jira-token

Did you follow it? Any user with permission to view your jira project would work for this action

**Comment by leovanhaaren** [comment]
> @leovanhaaren @hitmands it works correctly in my projects where I useAPI token, I guess you tried to use your password directly.
> please check this:
> https://github.com/cakeinpanic/jira-description-action#jira-token
> 
> Did you follow it? Any user with permission to view your jira project would work for this action

Thanks, seems to work now!

**Comment by cyrus-za** [comment]
This does not work for me. I did follow it. 

```sh
 response: {
      status: 401,
      statusText: 'Unauthorized',
      headers: [Object],
      config: [Object],
      request: [ClientRequest],
      data: 'Basic authentication with passwords is deprecated.  For more information, see: https://confluence.atlassian.com/cloud/deprecation-of-basic-authentication-with-passwords-for-jira-and-confluence-apis-972355348.html\n'
    },
    isAxiosError: true,
    toJSON: [Function]
  }
```

**Comment by hitmands** [comment]
This worked for me 
![image](https://user-images.githubusercontent.com/5674833/108755761-8f26b480-753f-11eb-8f0c-e92a46ece1fc.png)
