### ISSUE TITLE
Error: Cannot destructure property `login` of 'undefined' or 'null'

### ISSUE THREAD

**Issue by keshavprasadms** [cakeinpanic/jira-description-action#8]
I am not sure if I am doing something wrong, but I am getting this error when I try to use this workflow
```Run cakeinpanic/jira-description-action@v0.2.0
  with:
    github-token: ***
    jira-token: ***
    jira-base-url: ***
    use: both
{
  error: TypeError: Cannot destructure property `login` of 'undefined' or 'null'.
      at GithubConnector.getGithubData (/home/runner/work/_actions/cakeinpanic/jira-description-action/v0.2.0/lib/index.js:1:79753)
      at new GithubConnector (/home/runner/work/_actions/cakeinpanic/jira-description-action/v0.2.0/lib/index.js:1:78692)
      at /home/runner/work/_actions/cakeinpanic/jira-description-action/v0.2.0/lib/index.js:1:20760
      at Generator.next (<anonymous>)
      at /home/runner/work/_actions/cakeinpanic/jira-description-action/v0.2.0/lib/index.js:1:20508
      at new Promise (<anonymous>)
      at o (/home/runner/work/_actions/cakeinpanic/jira-description-action/v0.2.0/lib/index.js:1:20256)
      at run (/home/runner/work/_actions/cakeinpanic/jira-description-action/v0.2.0/lib/index.js:1:20670)
      at Object.131 (/home/runner/work/_actions/cakeinpanic/jira-description-action/v0.2.0/lib/index.js:1:21217)
      at __webpack_require__ (/home/runner/work/_actions/cakeinpanic/jira-description-action/v0.2.0/lib/index.js:1:169)
}
Error: Cannot destructure property `login` of 'undefined' or 'null'.
```

I have the secrets defined in my repo as `JIRA_BASE_URL` and `JIRA_TOKEN` (token of the form email:apitoken)

Actions file
```name: jira-description-action
on:
  pull_request:
    types: [opened, edited]
jobs:
  add-jira-description:
    runs-on: ubuntu-latest
    steps:
      - uses: cakeinpanic/jira-description-action@v0.2.0
        name: jira-description-action
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          jira-token: ${{ secrets.JIRA_TOKEN }}
          jira-base-url: ${{ secrets.JIRA_BASE_URL }}
          use: both
```

Please can someone assist?

**Comment by katyapavlenko** [comment]
@keshavprasadms you are running this action in a repo that does not belong to any organization, so the structure of github answer is different from what the code relays on
This is a bug which should be fixed, unfortunately I'd have time for it only next week 

Problem is in this method https://github.com/cakeinpanic/jira-description-action/blob/3354ca489f2c58364dcef2925efdb31b356be526/src/github-connector.ts#L65

**Comment by cakeinpanic** [comment]
@keshavprasadms you are running this action in a repo that does not belong to any organization, so the structure of github answer is different from what the code relays on
This is a bug which should be fixed, unfortunately I'd have time for it only next week 

Problem is in this method https://github.com/cakeinpanic/jira-description-action/blob/3354ca489f2c58364dcef2925efdb31b356be526/src/github-connector.ts#L65

**Comment by keshavprasadms** [comment]
Thanks @cakeinpanic. I created an orgranization to work around the problem for now and its working.
